[[config]]
project_name = "Atba"
bot_configs = ["atba.bot.toml"]

[config.builder_config]
builder_type = "csharp"
# Optional, use if there are multiple sub-projects that can be built
# base_dir = "Bot"
